### ISSUE TITLE
AWS Lambda Error "No module named 'cv2'"

### ISSUE THREAD

**Issue by WaterKnight1998** [iandow/opencv_aws_lambda#3]
Hi,

I run all your commands from your readme in a EC2 tiny linux 1 with docker installed. I uploaded the generated zip as a layer and added this layer to the function.

However, `import cv2` throws next error `"No module named 'cv2'"`.

Best regards,
WaterKnight

**Comment by iandow** [comment]
Sorry, I just saw this. Double check that you're importing cv2 within the lambda_handler function and not above it. Also use the AWS Lambda webui to double check that your layer is in fact attached.

**Comment by ktemby** [comment]
I had the same issue, but found that once I switched to python 3.6 I had no issues.

**Comment by matymad** [comment]
In my case it worked with python 3.7. 

I was testing with python 3.8 and didn't work.

**Comment by rfmac-caf** [comment]
Any workaround for python 3.8 and above?
